name: Checks

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 14 * * 1"

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Lint Awesome list
        run: npx -y awesome-lint README.md
      - name: Check README links
        run: npx -y markdown-link-check README.md
      - name: Check contributing links
        run: npx -y markdown-link-check CONTRIBUTING.md
